config/routes.rb
PeddieTaxi::Application.routes.draw do
  resources :venues do
    resources :proposals do
      resources :accommodations do
        resources :signups
      end
      resources :signups
    end
  end

  resources :proposals

  post '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

  root to: 'venues#index'

end

app/models/signup.rb
class Signup < ActiveRecord::Base
  belongs_to :user
  belongs_to :proposal
  belongs_to :accommodation
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  set_tab :signups
  before_action :set_signup, only: [:show, :edit, :update, :destroy]

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new

    # begin
    #   @venue = Venue.find(params[:venue_id])
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to venues_path, alert: 'You must select a valid venue first.'
    # end
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)
    @signup.user = current_user

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'signup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @signup }
      else
        format.html { render action: 'new' }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'signup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:proposal_id)
    end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signups/_accommodation.html.erb
<h3>
  #<%= accommodation.proposal_id %>
  <%= link_to "Sign up", { :controller => "signups",
                           :action => "new",
                           :accommodation_id => accommodation.id,
                           :proposal_id => accommodation.proposal_id },
                         { :class => "btn btn-primary btn-mini" } %>
</h3>
<%= accommodation.leaving_at %> to <%= accommodation.returning_at %>

<% accommodation.signups.each do |signup| %>
  <%= debug(signup) %>
<% end %>

app/views/signups/_form.html.erb
<%# h1, span12 %>
<% content_for :scripts do %>
  <%#= javascript_include_tag "accommodations" %>
<% end %>
<div class="span9">
  <div class="page-header">
    <h1><%= h1 %></h1>
  </div>
  <%= form_for record, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @signup.errors.any? %>
      <div id="error_explanation" class="alert alert-block alert-error">
        <strong><%= pluralize(@signup.errors.count, "error") %> prohibited this accommodation from being saved:</strong>
        <ul>
        <% @signup.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label :proposal_id, :class => 'control-label' %>
        <div class="controls">
          <div class="well">
            <div class="media">
              <div class="pull-left">
                <%= static_map_tag @proposal.venue.latitude, 
                                   @proposal.venue.longitude,
                                   :name => @proposal.venue.name %>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= @proposal.venue.name %></h4>
                <%= @proposal.venue.vicinity %><br />
                <%= @proposal.relative_week %>
              </div>
            </div>
          </div>
          <%= f.hidden_field :proposal_id, 
                             { :value => @proposal.id } %>
        </div>
    </div>

    <div class="control-group">
      <%= f.label :accommodation_id, :class => 'control-label' %>
        <div class="controls">
          <% unless @accommodation.blank? %>
            <div class="well">
              <div class="media">
                <div class="pull-left">
                <%= gravatar_image_tag @accommodation.try(:user).try(:email), 
                                       :gravatar => { 
                                                      :default => 'http://octodex.github.com/images/forktocat.jpg',
                                                      :size => 90 } %>
                </div>
                <div class="media-body">
                  <h4 class="media-heading"><%= @accommodation.try(:user).try(:full_name) %></h4>
                  <%= @accommodation.leaving_at %>&ndash;<%= @accommodation.returning_at %>
                </div>
              </div>
            </div>
          <% else %>
            <span class="help-block">You are signing up for the wait list.</span>
            <!-- TODO: grammar check -->
            <span class="help-block">You will be moved to an accommodation as they become available.</span>
            <span class="help-block">Set a broader time span to increase the likelihood of your request being fulfilled.</span>
          <% end %>
          <%= f.hidden_field :accommodation_id, 
                             { :value => @accommodation.try(:id) } %>
        </div>
    </div>

    

    <div class="form-actions">
      <%= f.submit "Confirm Signup", :class => 'btn btn-primary' %>
      <%= link_to "Cancel",
                  venue_proposal_accommodations_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/signups/edit.html.erb
<%# h1, span12 %>
<div class="row">
  <%= render :partial => 'form', :locals => { :h1 => "Edit an accommodation" } %>
</div>

app/views/signups/new.html.erb
<%
case @accommodation.blank?
when true
  h1 = "Sign up for wait list"
  record = [@proposal.venue, @proposal, @signup]
when false
  h1 = "Sign up for accommodation"
  record = [@proposal.venue, @proposal, @accommodation, @signup]
end
%>
<div class="row">
  <%= render :partial => 'form', :locals => { :h1 => h1,
                                              :record => record } %>
</div>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue:</strong>
  <%= @accommodation.venue_id %>
</p>

<p>
  <strong>Rides:</strong>
  <%= @accommodation.rides_id %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @accommodation.comments %>
</p>


<%= link_to 'Edit', edit_accommodation_path(@accommodation) %> |
<%= link_to 'Back', accommodations_path %>