config/routes.rb
PeddieTaxi::Application.routes.draw do
  resources :venues do
    resources :proposals do
      resources :accommodations do
        resources :signups
      end
      resources :signups
    end
  end

  resources :proposals

  post '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

  root to: 'venues#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :proposals
  belongs_to :user
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  set_tab :venues
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @proposal_this_week = @venue.proposals.this_week.first
    @proposal_next_week = @venue.proposals.next_week.first
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @venue }
      else
        format.html { render action: 'new' }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :latitude, :longitude, :description, :address, :vicinity, :reference)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%# h1, span12 %>
<%# 
  # TODO: better client_side_validations integration using this https://github.com/bcardarella/client_side_validations#customize-error-rendering
%>
<% content_for :scripts do %>
  <%= javascript_include_tag "map" %>
<% end %>
<div class="span6">
  <div class="page-header">
    <h1><%= h1 %></h1>
    <% if params[:action] == "new" %>
      <p class="text-info">Use the Autocomplete field below to have Peddie Taxi automatically fill out the form for you using information from Google Maps.  Review the information below and you are good to post your first proposal!</p>
      <p class="text-warning"><span class="label label-important">Important</span> Please make sure the venue you are trying to add doesn&rsquo;t exist in our system yet.  We delete duplicates, in addition to any requests 
      associated to duplicates.</p>
    <% end %>
  </div>
  <div class="page-header">
    <h2>Autocomplete</h2>
    <p class="text-info">Type an address below and we will try to fill in as much as we can for you!</p>
    <% if params[:action] == "edit" %>
      <p class="text-warning"><span class="label label-important">Warning!</span> You are editing a venue.  If you use autocomplete here, <strong>everything in the form will be overwritten</strong>, including the &ldquo;Description&rdquo;.</p>
    <% end %>
    <input id="google_autocomplete" 
           type="text" 
           class="text_field input-block-level"
           data-autocomplete-type="establishment"
           data-autocomplete-output-name="#venue_name"
           data-autocomplete-output-formatted-address="#venue_address"
           data-autocomplete-output-vicinity="#venue_vicinity"
           data-autocomplete-output-website="#venue_description"
           data-autocomplete-output-reference="#venue_reference" />
  </div>

  <%= form_for @venue, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @venue.errors.any? %>
      <div id="error_explanation" class="alert alert-block alert-error">
          <strong><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</strong>
          <ul>
          <% @venue.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, { :class => 'input-block-level',
                                  :placeholder => "e.g. Target" } %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address, { :class => 'input-block-level',
                                     :placeholder => "e.g. 70 Princeton Hightstown Road, East Windsor, NJ, United States" } %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :vicinity, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :vicinity, { :class => 'input-block-level',
                                      :placeholder => "e.g. 70 Princeton Hightstown Road, East Windsor" } %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :latitude, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :latitude, { :class => 'input-block-level',
                                      :placeholder => "please drag the pin..." } %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :longitude, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :longitude, { :class => 'input-block-level',
                                       :placeholder => "...for automatic filling" } %>
      </div>        
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, { :class => 'text_area input-block-level',
                                        :rows => 5,
                                        :placeholder => "Optional" } %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :reference, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :reference, { :class => 'input-block-level',
                                       :placeholder => "Internal use only" } %>
          <span class="help-block">Do not hack the system by attempting to fill it in manually.</span>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to "Cancel",
                  venues_path, :class => 'btn' %>
    </div>
  <% end %>
</div>
<div class="span6">
  <div class="map-data-source"
       data-base-latitude="<%= Settings.geo.locations.base.latitude %>"
       data-base-longitude="<%= Settings.geo.locations.base.longitude %>"></div>
  <div class="map well" 
       data-base-latitude="<%= Settings.geo.locations.base.latitude %>"
       data-base-longitude="<%= Settings.geo.locations.base.longitude %>"
       data-enable-draggable-marker="true"
       data-draggable-marker-handle
       data-draggable-marker-sync-lat="input#venue_latitude"
       data-draggable-marker-sync-lon="input#venue_longitude"
       data-draggable-marker-title="New venue"></div>
</div>

app/views/venues/_list_item.html.erb
<%# display div.venue-list_item's, incl. its name, action btns %>
<%# h2, span4 %>
<div class="venue-list_item" 
  data-latitude="<%= venue.latitude %>"
  data-longitude="<%= venue.longitude %>"
  data-name="<%= venue.name %>">

  <div class="row">
    <div class="span4">
      <h2><%= link_to venue.name, venue_path(venue) %></h2>
    </div>
  </div>

</div>

app/views/venues/edit.html.erb
<%# pinpoint, get lat/long, ask for name, type %>
<%# h1, span12 %>
<div class="row">
  <%= render :partial => 'form', :locals => { :h1 => "Edit venue",
                                              :@venue => @venue } %>
</div>

app/views/venues/index.html.erb
<%# h1, span12 %>
<% content_for :scripts do %>
  <%= javascript_include_tag "map" %>
<% end %>
<div class="row">
  <div class="span8">
    <div class="map well"
         data-base-latitude="<%= Settings.geo.locations.base.latitude %>"
         data-base-longitude="<%= Settings.geo.locations.base.longitude %>">
    </div>
  </div>
  <div class="span4">
    <div class="page-header">
      <h1>Venues <%= link_to "Add New", new_venue_path, :class => 'btn btn-primary' %></h1>
    </div>
    <div class="venue-list map-data-source">
      <% @venues.each do |venue| %>
        <%= render 'list_item', :venue => venue %>
      <% end %>
    </div>
  </div>
</div>

app/views/venues/new.html.erb
<%# pinpoint, get lat/long, ask for name, type %>
<%# h1, span12 %>
<div class="row visible-phone">
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>The map has been moved below the form</strong> because of 
    insufficient horizontal space.  If you are on a laptop or desktop, maximize 
    the window to get the best experience.
  </div>
</div>
<div class="row">
  <%= render :partial => 'form', :locals => { :h1 => "Add a venue first" } %>
</div>

app/views/venues/show.html.erb
<% content_for :scripts do %>
  <%= javascript_include_tag "map" %>
<% end %>

<div class="hero-unit">
  <h1><%= @venue.name %></h1>
  <p><%= @venue.vicinity %></p>
  <p>
    <%= link_to "Propose a trip", { :controller => "proposals",
                                  :action => "new",
                                  :venue_id => @venue.id },
                                { :class => "btn btn-primary btn-large" } %>
    <%= link_to "Edit", edit_venue_path, { :class => "btn btn-large" } %>
    <%= link_to "Delete", {}, { :confirm => "Are you sure?", 
                                :method => :delete, 
                                :class => "btn btn-danger btn-large" } %>
  </p>
</div>

<div class="row">
  <div class="span8">
    <div class="page-header">
      <h2>About this venue</h2>
    </div>
    <table class="table table-bordered table-hover map-data-source">
      <tbody>
        <tr>
          <th scope="row">Description</th>
          <td><%= simple_format( @venue.description ) %></td>
        </tr>
        <tr>
          <th scope="row">Popularity</th>
          <td>? people have requested to get here</td>
        </tr>
        <tr class="additional-data">
          <th scope="row">Geographical data</th>
          <td>
            <div id="destination" class="venue-list_item"
              data-latitude="<%= @venue.latitude %>"
              data-longitude="<%= @venue.longitude %>"></div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span4">
    <div class="page-header">
      <h2>Recent proposals</h2>
    </div>
    <h3>This week</h3>
    <h3>Next week</h3>
  </div>
</div>

<div class="row">
  <div class="span12">
    <div class="page-header">
      <h2>Directions <small>see estimated travel time and turn-by-turn direction</small></h2>
    </div>
  </div>
  <div class="span6">
    <div id="alert_select_travel_mode" class="alert alert-info">
      Select a travel mode to start planning the route.
    </div>
    <div id="travel_mode_selector" class="btn-group">
      <button type="button" class="btn btn-primary" value="WALKING">Walking</button>
      <button type="button" class="btn btn-primary" value="BICYCLING">Bicycling</button>
      <button type="button" class="btn btn-primary" value="DRIVING">Driving</button>
    </div>
    <div id="directions_panel"></div>
  </div>
  <div class="span6">
    <div class="map well"
      data-base-latitude="<%= Settings.geo.locations.base.latitude %>"
      data-base-longitude="<%= Settings.geo.locations.base.longitude %>"
      data-enable-direction="true"
      data-travel-mode-selector="#travel_mode_selector button"
      data-hide-once-travel-mode-is-selected="#alert_select_travel_mode"
      data-destination-selector=".map-data-source #destination"
      data-enable-direction-display="true"
      data-direction-display-target="#directions_panel"></div>
  </div>
</div>