config/routes.rb
PeddieTaxi::Application.routes.draw do
  resources :venues do
    resources :proposals do
      resources :accommodations do
        resources :signups
      end
      resources :signups
    end
  end

  resources :proposals

  post '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

  root to: 'venues#index'

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :venue
  belongs_to :user
  has_many :signups
  has_many :accommodations


  def self.this_week_year
    DateTime.now.strftime("%Y").to_i
  end

  def self.this_week_number
    DateTime.now.strftime("%V").to_i
  end

  def self.next_week_year
    1.week.from_now.strftime("%Y").to_i
  end

  def self.next_week_number
    1.week.from_now.strftime("%V").to_i
  end

  def self.this_week
    where("year = ?", self.this_week_year).where("week = ?", self.this_week_number)
  end

  def self.next_week
    where("year = ?", self.next_week_year).where("week = ?", self.next_week_number)
  end


  def relative_week
    case 
    when year == self.class.this_week_year && week == self.class.this_week_number
      return :this_week
    when year == self.class.next_week_year && week == self.class.next_week_number
      return :next_week
    else
      :some_other_week
    end
  end


  def relative_week=(this_week_or_next_week)
    if this_week_or_next_week == "next_week"
      self.year = self.class.next_week_year
      self.week = self.class.next_week_number
    else
      self.year = self.class.this_week_year
      self.week = self.class.this_week_number
    end
  end

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  set_tab :proposals
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  # GET /proposals.json
  def index
    # @proposals_this_week = Proposal.this_week
    # @proposals_next_week = Proposal.next_week
    redirect_to :controller => :venues, 
                :action => :show, 
                :id => params[:venue_id]
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @wait_list = @proposal.signups.select { |s| s.accommodation_id == nil }
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new

    begin
      @venue = Venue.find(params[:venue_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to venues_path, alert: 'You must select a valid venue first.'
    end
  end

  # GET /proposals/1/edit
  def edit
    @venue = @proposal.venue
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.user = current_user

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to [@proposal.venue, @proposal], notice: 'Proposal was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to [@proposal.venue, @proposal], notice: 'Proposal was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:venue_id, :relative_week, :comments)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<% content_for :scripts do %>
  <%= javascript_include_tag "proposals" %>
<% end %>
<div class="span9">
  <div class="page-header">
    <h1><%= h1 %></h1>
    <% if params[:action] == "new" %>
      <p class="text-info">Fill in this form and get your friends to sign up for it.</p>
      <p class="text-warning">Look for existing proposals before creating a new one, or you might get a validation error when you submit!</p>
    <% end %>
  </div>
  <%= form_for [@venue, @proposal], :html => { :class => 'form-horizontal' } do |f| %>
    <% if @proposal.errors.any? %>
      <div id="error_explanation" class="alert alert-block alert-error">
        <strong><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</strong>
        <ul>
        <% @proposal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label :venue_id, :class => 'control-label' %>
        <div class="controls">
          <% if @venue.present? %>
            <div class="well">
              <div class="media">
                <div class="pull-left">
                  <%= static_map_tag @venue.latitude, @venue.longitude,
                                     :name => @venue.name %>
                </div>
                <div class="media-body">
                  <h4 class="media-heading"><%= @venue.name %></h4>
                  <%= @venue.vicinity %>
                </div>
              </div>
            </div>
            <%= f.hidden_field :venue_id, 
                               { :value => @venue.id } %>
          <% else %>
            <div class="alert alert-error">
              Invalid venue.  Enter venue ID manually below.
            </div>
            <%= f.text_field :venue_id, 
                             { :class => 'text_field input-small' } %>
          <% end %>
        </div>
    </div>

    <div class="control-group">
      <%= f.label :week, :class => 'control-label' %>
      <div class="controls">
        <div id="relative_week" class="btn-group" data-toggle="buttons-radio">
          <button type="button"
                  class="btn <%= active_if_val_eq(@proposal.relative_week, :this_week) %>"
                  value="this_week">
            This week
          </button>
          <button type="button" 
                  class="btn <%= active_if_val_eq(@proposal.relative_week, :next_week) %>" 
                  value="next_week">
            Next week
          </button>
        </div>
        <%= f.hidden_field :relative_week %>
        <span class="help-block">The week starts with Sunday.</span>
        <span class="help-block">
          You will be able to refine the timespan when you sign up.
        </span>
        <span class="help-block">
          Faculty members specify exact departure time when they offer accommodations.
        </span>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :comments, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :comments, { :class => 'text_area input-block-level' } %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to "Cancel",
                  venue_proposals_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/proposals/edit.html.erb
<%# h1, span12 %>
<div class="row">
  <%= render :partial => 'form', :locals => { :h1 => "Edit proposal" } %>
</div>

app/views/proposals/index.html.erb
<div class="row">
  <div class="span9 this_week">
    <div class="page-header">
      <h2>This week</h2>
    </div>
    <% @proposals_this_week.each do |proposal| %>
      <div class="media span4">
        <a class="pull-left" href='<%= url_for :controller => :proposals, :action => :show, :venue_id => proposal.venue_id, :id => proposal.id %>'>
          <%= static_map_tag proposal.venue.latitude, proposal.venue.longitude,
                             :height => 130, :width => 130,
                             :class => "media-object" %>
        </a>
        <div class="media-body">
          <h3><%= link_to proposal.venue.name, {:controller => :proposals, :action => :show, :venue_id => proposal.venue_id, :id => proposal.id} %></h3>
          <%= proposal.relative_week %>
          <%= simple_format(proposal.comments) %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="span9 next_week">
    <div class="page-header">
      <h2>Next week</h2>
    </div>
    <% @proposals_next_week.each do |proposal| %>
      <div class="media span3">
        <a class="pull-left" href='<%= url_for proposal %>'>
          <%= static_map_tag proposal.venue.latitude, proposal.venue.longitude,
                             :height => 100, :width => 100,
                             :class => "media-object" %>
        </a>
        <div class="media-body">
          <h3><%= link_to proposal.venue.name, proposal %></h3>
          <%= proposal.relative_week %>
          <%= simple_format(proposal.comments) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/proposals/new.html.erb
<%# h1, span12 %>
<div class="row">
  <%= render :partial => 'form', :locals => { :h1 => "Add a proposal" } %>
</div>

app/views/proposals/show.html.erb
<div class="hero-unit">
  <p><%= proposal_status_badge(@proposal) %></p>
  <h1>Trip to <%= @proposal.venue.name %></h1>
  <p><%= @proposal.relative_week %></p>
  <p>
    <%= link_to "Accommodate", { :controller => "accommodations",
                                 :action => "new",
                                 :proposal_id => @proposal.id },
                           { :class => "btn btn-primary btn-large" } %>
    <%= link_to "View venue", @proposal.venue,
                              { :class => "btn btn-large" } %>
    <%= link_to "Edit", edit_venue_proposal_path, { :class => "btn btn-large" } %>
    <%= link_to "Delete", {}, { :data => { confirm: 'Are you sure?' },
                                :method => :delete, 
                                :class => "btn btn-danger btn-large" } %>
  </p>
</div>

<div class="row">
  <div class="span3">
    <div class="page-header">
      <h2>Roster</h2>
    </div>
    <% unless @proposal.accommodations.blank? %>
      <%= render @proposal.accommodations %>
    <% else %>
      <p class="text-warning">There are no accommodations yet.</p>
      <p class="text-info">Add yourself to the wait list first, and Peddie Taxi will automatically put you in an accommodation as they become available.</p>
    <% end %>
  </div>
  <div class="span3">
    <div class="page-header">
      <h2>Wait list</h2>
    </div>
    <%= link_to "Sign me up on wait list", 
                new_venue_proposal_signup_path(:proposal_id => @proposal.id),
                { :class => "btn btn-large btn-block btn-primary" } %>
    <%= debug @wait_list %>
    <%#= render @wait_list %>
  </div>
  <div class="span6">
    <div class="page-header">
      <h2>Trip information</h2>
    </div>
    <table class="table table-bordered table-hover map-data-source">
      <tbody>
        <tr>
          <th scope="row">Week</th>
          <td>
            <%= @proposal.year %>, <%= @proposal.relative_week %>
          </td>
        </tr>
        <tr>
          <th scope="row">Proposed by</th>
          <td><%= @proposal.try(:user).try(:name_and_graduation_year) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>