config/routes.rb
PeddieTaxi::Application.routes.draw do
  resources :venues do
    resources :proposals do
      resources :accommodations do
        resources :signups
      end
      resources :signups
    end
  end

  resources :proposals

  post '/auth/:provider/callback' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

  root to: 'venues#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><%= content_for?(:title) ? yield(:title) : "Peddie Taxi" %></title>
  
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= favicon_link_tag asset_path "favicon.ico", :rel => 'shortcut icon' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %> <%= params[:controller] %>_<%= params[:action] %>">

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Peddie Taxi", root_path, :class => "brand" %>
        <div class="nav-collapse collapse">
          <%= tabs_tag(:builder => ApplicationHelper::BootstrapNavTabBuilder) do |tab| %>
            <%= tab.proposals 'Proposals', '' %>
            <%= tab.venues    'Venues', venues_path %>
          <% end %>
          <div class="pull-right">
            <ul class="nav">
              <li>
                <% if signed_in? %>
                  <%= link_to '<i class="icon-user"></i> '.html_safe + "Sign out #{current_user.first_name}", "/sessions", :method => :delete %>
                <% else %>
                  <%= link_to '<i class="icon-user"></i> '.html_safe + "Peddie OpenID Sign-in", "/auth/peddie" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12">
        <% if flash[:notice] %>
          <p class="alert alert-info"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
          <p class="alert alert-error"><%= flash[:alert] %></p>
        <% end %>
      </div>
    </div>

    <%= yield %>

  </div>

  <%= yield :scripts %>

</body>
</html>